nohup sh  Files/Plant-rhizosphere/results/Plant-rhizosphere-1/Plant-rhizosphere-1-R2.sh >  Files/Plant-rhizosphere/results/Plant-rhizosphere-1/Plant-rhizosphere-1-R2.sh.log 2>&1 &
nohup sh  Files/Plant-rhizosphere/results/Plant-rhizosphere-2/Plant-rhizosphere-2-R2.sh >  Files/Plant-rhizosphere/results/Plant-rhizosphere-2/Plant-rhizosphere-2-R2.sh.log 2>&1 &
nohup sh  Files/Plant-rhizosphere/results/Plant-rhizosphere-3/Plant-rhizosphere-3-R2.sh >  Files/Plant-rhizosphere/results/Plant-rhizosphere-3/Plant-rhizosphere-3-R2.sh.log 2>&1 &
nohup sh  Files/Plant-rhizosphere/results/Plant-rhizosphere-4/Plant-rhizosphere-4-R2.sh >  Files/Plant-rhizosphere/results/Plant-rhizosphere-4/Plant-rhizosphere-4-R2.sh.log 2>&1 &
nohup sh  Files/Plant-rhizosphere/results/Plant-rhizosphere-5/Plant-rhizosphere-5-R2.sh >  Files/Plant-rhizosphere/results/Plant-rhizosphere-5/Plant-rhizosphere-5-R2.sh.log 2>&1 &
nohup sh  Files/Plant-rhizosphere/results/Plant-rhizosphere-6/Plant-rhizosphere-6-R2.sh >  Files/Plant-rhizosphere/results/Plant-rhizosphere-6/Plant-rhizosphere-6-R2.sh.log 2>&1 &
nohup sh  Files/Plant-rhizosphere/results/Plant-rhizosphere-7/Plant-rhizosphere-7-R2.sh >  Files/Plant-rhizosphere/results/Plant-rhizosphere-7/Plant-rhizosphere-7-R2.sh.log 2>&1 &
nohup sh  Files/Plant-rhizosphere/results/Plant-rhizosphere-8/Plant-rhizosphere-8-R2.sh >  Files/Plant-rhizosphere/results/Plant-rhizosphere-8/Plant-rhizosphere-8-R2.sh.log 2>&1 &
nohup sh  Files/Plant-rhizosphere/results/Plant-rhizosphere-9/Plant-rhizosphere-9-R2.sh >  Files/Plant-rhizosphere/results/Plant-rhizosphere-9/Plant-rhizosphere-9-R2.sh.log 2>&1 &
nohup sh  Files/Plant-rhizosphere/results/Plant-rhizosphere-10/Plant-rhizosphere-10-R2.sh >  Files/Plant-rhizosphere/results/Plant-rhizosphere-10/Plant-rhizosphere-10-R2.sh.log 2>&1 &
nohup sh  Files/Plant-rhizosphere/results/Plant-rhizosphere-11/Plant-rhizosphere-11-R2.sh >  Files/Plant-rhizosphere/results/Plant-rhizosphere-11/Plant-rhizosphere-11-R2.sh.log 2>&1 &
nohup sh  Files/Plant-rhizosphere/results/Plant-rhizosphere-12/Plant-rhizosphere-12-R2.sh >  Files/Plant-rhizosphere/results/Plant-rhizosphere-12/Plant-rhizosphere-12-R2.sh.log 2>&1 &
nohup sh  Files/Plant-rhizosphere/results/Plant-rhizosphere-13/Plant-rhizosphere-13-R2.sh >  Files/Plant-rhizosphere/results/Plant-rhizosphere-13/Plant-rhizosphere-13-R2.sh.log 2>&1 &
nohup sh  Files/Plant-rhizosphere/results/Plant-rhizosphere-14/Plant-rhizosphere-14-R2.sh >  Files/Plant-rhizosphere/results/Plant-rhizosphere-14/Plant-rhizosphere-14-R2.sh.log 2>&1 &
nohup sh  Files/Plant-rhizosphere/results/Plant-rhizosphere-15/Plant-rhizosphere-15-R2.sh >  Files/Plant-rhizosphere/results/Plant-rhizosphere-15/Plant-rhizosphere-15-R2.sh.log 2>&1 &
nohup sh  Files/Plant-rhizosphere/results/Plant-rhizosphere-16/Plant-rhizosphere-16-R2.sh >  Files/Plant-rhizosphere/results/Plant-rhizosphere-16/Plant-rhizosphere-16-R2.sh.log 2>&1 &
nohup sh  Files/Plant-rhizosphere/results/Plant-rhizosphere-17/Plant-rhizosphere-17-R2.sh >  Files/Plant-rhizosphere/results/Plant-rhizosphere-17/Plant-rhizosphere-17-R2.sh.log 2>&1 &
nohup sh  Files/Plant-rhizosphere/results/Plant-rhizosphere-18/Plant-rhizosphere-18-R2.sh >  Files/Plant-rhizosphere/results/Plant-rhizosphere-18/Plant-rhizosphere-18-R2.sh.log 2>&1 &
nohup sh  Files/Plant-rhizosphere/results/Plant-rhizosphere-19/Plant-rhizosphere-19-R2.sh >  Files/Plant-rhizosphere/results/Plant-rhizosphere-19/Plant-rhizosphere-19-R2.sh.log 2>&1 &
nohup sh  Files/Plant-rhizosphere/results/Plant-rhizosphere-20/Plant-rhizosphere-20-R2.sh >  Files/Plant-rhizosphere/results/Plant-rhizosphere-20/Plant-rhizosphere-20-R2.sh.log 2>&1 &
nohup sh  Files/Plant-rhizosphere/results/Plant-rhizosphere-21/Plant-rhizosphere-21-R2.sh >  Files/Plant-rhizosphere/results/Plant-rhizosphere-21/Plant-rhizosphere-21-R2.sh.log 2>&1 &
nohup sh  Files/Plant-rhizosphere/results/Plant-rhizosphere-22/Plant-rhizosphere-22-R2.sh >  Files/Plant-rhizosphere/results/Plant-rhizosphere-22/Plant-rhizosphere-22-R2.sh.log 2>&1 &
nohup sh  Files/Plant-rhizosphere/results/Plant-rhizosphere-23/Plant-rhizosphere-23-R2.sh >  Files/Plant-rhizosphere/results/Plant-rhizosphere-23/Plant-rhizosphere-23-R2.sh.log 2>&1 &
nohup sh  Files/Plant-rhizosphere/results/Plant-rhizosphere-24/Plant-rhizosphere-24-R2.sh >  Files/Plant-rhizosphere/results/Plant-rhizosphere-24/Plant-rhizosphere-24-R2.sh.log 2>&1 &
nohup sh  Files/Plant-rhizosphere/results/Plant-rhizosphere-25/Plant-rhizosphere-25-R2.sh >  Files/Plant-rhizosphere/results/Plant-rhizosphere-25/Plant-rhizosphere-25-R2.sh.log 2>&1 &
nohup sh  Files/Plant-rhizosphere/results/Plant-rhizosphere-26/Plant-rhizosphere-26-R2.sh >  Files/Plant-rhizosphere/results/Plant-rhizosphere-26/Plant-rhizosphere-26-R2.sh.log 2>&1 &
nohup sh  Files/Plant-rhizosphere/results/Plant-rhizosphere-27/Plant-rhizosphere-27-R2.sh >  Files/Plant-rhizosphere/results/Plant-rhizosphere-27/Plant-rhizosphere-27-R2.sh.log 2>&1 &
nohup sh  Files/Plant-rhizosphere/results/Plant-rhizosphere-28/Plant-rhizosphere-28-R2.sh >  Files/Plant-rhizosphere/results/Plant-rhizosphere-28/Plant-rhizosphere-28-R2.sh.log 2>&1 &
nohup sh  Files/Plant-rhizosphere/results/Plant-rhizosphere-29/Plant-rhizosphere-29-R2.sh >  Files/Plant-rhizosphere/results/Plant-rhizosphere-29/Plant-rhizosphere-29-R2.sh.log 2>&1 &
nohup sh  Files/Plant-rhizosphere/results/Plant-rhizosphere-30/Plant-rhizosphere-30-R2.sh >  Files/Plant-rhizosphere/results/Plant-rhizosphere-30/Plant-rhizosphere-30-R2.sh.log 2>&1 &
nohup sh  Files/Plant-rhizosphere/results/Plant-rhizosphere-31/Plant-rhizosphere-31-R2.sh >  Files/Plant-rhizosphere/results/Plant-rhizosphere-31/Plant-rhizosphere-31-R2.sh.log 2>&1 &
nohup sh  Files/Plant-rhizosphere/results/Plant-rhizosphere-32/Plant-rhizosphere-32-R2.sh >  Files/Plant-rhizosphere/results/Plant-rhizosphere-32/Plant-rhizosphere-32-R2.sh.log 2>&1 &
nohup sh  Files/Plant-rhizosphere/results/Plant-rhizosphere-33/Plant-rhizosphere-33-R2.sh >  Files/Plant-rhizosphere/results/Plant-rhizosphere-33/Plant-rhizosphere-33-R2.sh.log 2>&1 &
nohup sh  Files/Plant-rhizosphere/results/Plant-rhizosphere-34/Plant-rhizosphere-34-R2.sh >  Files/Plant-rhizosphere/results/Plant-rhizosphere-34/Plant-rhizosphere-34-R2.sh.log 2>&1 &
nohup sh  Files/Plant-rhizosphere/results/Plant-rhizosphere-35/Plant-rhizosphere-35-R2.sh >  Files/Plant-rhizosphere/results/Plant-rhizosphere-35/Plant-rhizosphere-35-R2.sh.log 2>&1 &
nohup sh  Files/Plant-rhizosphere/results/Plant-rhizosphere-36/Plant-rhizosphere-36-R2.sh >  Files/Plant-rhizosphere/results/Plant-rhizosphere-36/Plant-rhizosphere-36-R2.sh.log 2>&1 &
nohup sh  Files/Plant-rhizosphere/results/Plant-rhizosphere-37/Plant-rhizosphere-37-R2.sh >  Files/Plant-rhizosphere/results/Plant-rhizosphere-37/Plant-rhizosphere-37-R2.sh.log 2>&1 &
nohup sh  Files/Plant-rhizosphere/results/Plant-rhizosphere-38/Plant-rhizosphere-38-R2.sh >  Files/Plant-rhizosphere/results/Plant-rhizosphere-38/Plant-rhizosphere-38-R2.sh.log 2>&1 &
nohup sh  Files/Plant-rhizosphere/results/Plant-rhizosphere-39/Plant-rhizosphere-39-R2.sh >  Files/Plant-rhizosphere/results/Plant-rhizosphere-39/Plant-rhizosphere-39-R2.sh.log 2>&1 &
nohup sh  Files/Plant-rhizosphere/results/Plant-rhizosphere-40/Plant-rhizosphere-40-R2.sh >  Files/Plant-rhizosphere/results/Plant-rhizosphere-40/Plant-rhizosphere-40-R2.sh.log 2>&1 &
nohup sh  Files/Plant-rhizosphere/results/Plant-rhizosphere-41/Plant-rhizosphere-41-R2.sh >  Files/Plant-rhizosphere/results/Plant-rhizosphere-41/Plant-rhizosphere-41-R2.sh.log 2>&1 &
nohup sh  Files/Plant-rhizosphere/results/Plant-rhizosphere-42/Plant-rhizosphere-42-R2.sh >  Files/Plant-rhizosphere/results/Plant-rhizosphere-42/Plant-rhizosphere-42-R2.sh.log 2>&1 &
nohup sh  Files/Plant-rhizosphere/results/Plant-rhizosphere-43/Plant-rhizosphere-43-R2.sh >  Files/Plant-rhizosphere/results/Plant-rhizosphere-43/Plant-rhizosphere-43-R2.sh.log 2>&1 &
nohup sh  Files/Plant-rhizosphere/results/Plant-rhizosphere-44/Plant-rhizosphere-44-R2.sh >  Files/Plant-rhizosphere/results/Plant-rhizosphere-44/Plant-rhizosphere-44-R2.sh.log 2>&1 &
nohup sh  Files/Plant-rhizosphere/results/Plant-rhizosphere-45/Plant-rhizosphere-45-R2.sh >  Files/Plant-rhizosphere/results/Plant-rhizosphere-45/Plant-rhizosphere-45-R2.sh.log 2>&1 &
nohup sh  Files/Plant-rhizosphere/results/Plant-rhizosphere-46/Plant-rhizosphere-46-R2.sh >  Files/Plant-rhizosphere/results/Plant-rhizosphere-46/Plant-rhizosphere-46-R2.sh.log 2>&1 &
nohup sh  Files/Plant-rhizosphere/results/Plant-rhizosphere-47/Plant-rhizosphere-47-R2.sh >  Files/Plant-rhizosphere/results/Plant-rhizosphere-47/Plant-rhizosphere-47-R2.sh.log 2>&1 &
nohup sh  Files/Plant-rhizosphere/results/Plant-rhizosphere-48/Plant-rhizosphere-48-R2.sh >  Files/Plant-rhizosphere/results/Plant-rhizosphere-48/Plant-rhizosphere-48-R2.sh.log 2>&1 &
nohup sh  Files/Plant-rhizosphere/results/Plant-rhizosphere-49/Plant-rhizosphere-49-R2.sh >  Files/Plant-rhizosphere/results/Plant-rhizosphere-49/Plant-rhizosphere-49-R2.sh.log 2>&1 &
nohup sh  Files/Plant-rhizosphere/results/Plant-rhizosphere-50/Plant-rhizosphere-50-R2.sh >  Files/Plant-rhizosphere/results/Plant-rhizosphere-50/Plant-rhizosphere-50-R2.sh.log 2>&1 &
